services:
  flask_app:
    build: ./flask_app
    container_name: flask_container
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - web_app_network
    volumes:
      - ./flask_app:/app

  django_app:
    build: ./django_app
    container_name: django_container
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - web_app_network
    volumes:
      - ./django_app:/app

networks:
  web_app_network:
    driver: bridge